/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Data object for BestScore.
 * @lomboz generated
 */
public class BestScoreData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.String name;
   private int score;

  /* begin value object */

  /* end value object */

   public BestScoreData()
   {
   }

   public BestScoreData( java.lang.String name,int score )
   {
      setName(name);
      setScore(score);
   }

   public BestScoreData( BestScoreData otherData )
   {
      setName(otherData.getName());
      setScore(otherData.getScore());

   }

   public java.lang.String getPrimaryKey() {
     return  getName();
   }

   public java.lang.String getName()
   {
      return this.name;
   }
   public void setName( java.lang.String name )
   {
      this.name = name;
   }

   public int getScore()
   {
      return this.score;
   }
   public void setScore( int score )
   {
      this.score = score;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("name=" + getName() + " " + "score=" + getScore());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof BestScoreData )
      {
         BestScoreData lTest = (BestScoreData) pOther;
         boolean lEquals = true;

         if( this.name == null )
         {
            lEquals = lEquals && ( lTest.name == null );
         }
         else
         {
            lEquals = lEquals && this.name.equals( lTest.name );
         }
         lEquals = lEquals && this.score == lTest.score;

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.name != null) ? this.name.hashCode() : 0);

      result = 37*result + (int) score;

      return result;
   }

}
