/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Local interface for BestScore.
 * @lomboz generated
 */
public interface BestScoreLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Returns the name
    * @return the name
    */
   public java.lang.String getName(  ) ;

   /**
    * Sets the name
    * @param java.lang.String the new name value
    */
   public void setName( java.lang.String name ) ;

   /**
    * Returns the score
    * @return the score
    */
   public int getScore(  ) ;

   /**
    * Sets the score
    * @param java.lang.Integer the new score value
    */
   public void setScore( int score ) ;

}
