/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Local home interface for BestScore.
 * @lomboz generated
 */
public interface BestScoreLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BestScoreLocal";
   public static final String JNDI_NAME="BestScoreLocal";

   public numguess.ejb.BestScoreLocal create(java.lang.String name)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public numguess.ejb.BestScoreLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
