/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Local home interface for GameLogic.
 * @lomboz generated
 */
public interface GameLogicLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GameLogicLocal";
   public static final String JNDI_NAME="GameLogicLocal";

   public numguess.ejb.GameLogicLocal create()
      throws javax.ejb.CreateException;

}
