/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Local interface for GameLogic.
 * @lomboz generated
 */
public interface GameLogicLocal
   extends javax.ejb.EJBLocalObject
{

   public numguess.common.GuessResult guess( int guess ) ;

   public void reset(  ) ;

}
