/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Session layer for GameLogic.
 * @lomboz generated
 */
public class GameLogicSession
   extends numguess.ejb.GameLogicBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
