/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Home interface for Range.
 * @lomboz generated
 */
public interface RangeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Range";
   public static final String JNDI_NAME="RangeBean";

   public numguess.ejb.Range create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
