/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Session layer for Range.
 * @lomboz generated
 */
public class RangeSession
   extends numguess.ejb.RangeBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
