/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Local home interface for Range.
 * @lomboz generated
 */
public interface RangeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RangeLocal";
   public static final String JNDI_NAME="RangeLocal";

   public numguess.ejb.RangeLocal create()
      throws javax.ejb.CreateException;

}
