/*
 * Generated by XDoclet - Do not edit!
 */
package numguess.ejb;

/**
 * Local interface for Range.
 * @lomboz generated
 */
public interface RangeLocal
   extends javax.ejb.EJBLocalObject
{

   public numguess.common.RangeResult getRange(  ) ;

}
